name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 监视主分支推送（根据实际源码分支名调整）
permissions:
  contents: write       # 允许此 workflow 使用GITHUB_TOKEN推送代码
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装系统依赖
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick python3-pip
          pip3 install --upgrade pip
          pip3 install jupyter

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Install Bundler dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "_site"
          branch: "gh-pages"
          clean: true    # 部署前清空旧文件
          # 注：该Action会使用默认的GITHUB_TOKEN推送，已在permissions中授权
